version: "3.7"

services:
  postgres:
    image: 'postgres:12.12'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - env_net
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - env_net

  apps:
    user: $UID:$GID
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    # command: >
    #   sh -c "python manage.py migrate &&
    #     python manage.py runserver 0.0.0.0:8000"
    networks:
      - env_net
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  # elasticsearch:
  #   image: elasticsearch:8.2.3
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   networks:
  #     - env_net
  #   restart: always

  # kibana:
  #   image: kibana:8.2.3
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - env_net
  #   restart: always
  
volumes:
  database-data:
  pgadmin:
  # elasticsearch-data:

networks:
  env_net:
    driver: bridge
